entrypoint: gunicorn -b :$PORT main:app -w 2 -t 200

runtime: python38

env_variables:
    DEV: False

automatic_scaling:
git commit -m "git push origin your-branch
  min_instances: 1
  max_instances: 1000
  max_concurrent_requests: 1 
