entrypoint: gunicorn -b :$PORT main:app -w 2 -t 200

runtime: python38

env_variables:
    DEV: False

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 5
  max_instances: 100
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
