entrypoint: gunicorn -b :8080 "SlothAI:create_app(conf='prod')" -w 2 -t 200
service_account: sloth-ai@appspot.gserviceaccount.com
runtime: python38

automatic_scaling:
  min_instances: 1
  max_instances: 1000
  max_concurrent_requests: 1 
